### ISSUE TITLE
Ссылка для web просмотра базы

### ISSUE THREAD

**Issue by ghost** [xintrea/mytetra_syncro#1]
К документации - [webhamster.ru/site/page/index/articles/projectcode/267](https://webhamster.ru/site/page/index/articles/projectcode/267)
ссылку для web просмотра надо делать так (raw в другом месте) :
`https://webhamster.ru/mytetrashare/index/https:~~github.com~XXXXXXXXX~mytetra~raw~master~mytetra.xml`
тогда всё работает.
Иначе корневой xml зависает в какой-то старой версии (отображает старый name,tags, нету новых ветвей)
;)
P.S. Ха. Не совсем так. По  `https:~~raw~github.com...` выдаёт совсем старое (первое?), а по `...raw~master...` выдаёт старое, но не настолько старое. Чудеса ;)

**Comment by xintrea** [comment]
Github немного тормозит с обновлениями raw-файлов. Задержка где-то около 5 минут может быть.
